FROM python:3.12-slim

WORKDIR /frontend

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHON UNBUFFERED 1
ENV DOCKER_RUNNING True


# Install system dependencies
RUN apt-get update && apt-get install -y \
    tk

RUN pip install --upgrade pip
RUN pip install pipenv

# Install dependencies
COPY ./Pipfile Pipfile
RUN pipenv install --skip-lock --system --dev

COPY . .
