version: "3.7"

services:
  store_data_api:
    build: 
      context: ./
      dockerfile: Dockerfile
    # image: osomova/moderate_store_data_api:dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004
    ports:
      - 8004:8004
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
